export const CheckBox = {
  name: "CheckBox1",
  type: "CheckBox",
  caption: "CheckBox1",
  accelerator:"",
  autoSize:false,
  controlSource: "",
  controlTipText: "",
  enabled: true,
  groupName: "",
  helpContextId: 0,
  locked: false,
  mouseIcon: "(None)",
  picture: "(None)",
  picturePosition: "7 - fmPicturePositionAboveCenter",
  tabindex: 9,
  tabStop: true,
  tag: "",
  tripleState: false,
  value: "",
  visible: true,
  left: "20px",
  top: "100px",
  width: "100px",
  height: "40px",
  zIndex: "1",
  backColor: "white",
  borderColor: "#eeeeee",
  border: "1px solid",
  borderStyle: "solid",
  font: "Arial, Helvetica, sans-serif",
  foreColor: "black",
  textAlign: "left",
  cursor: "default",
  specialEffect: "none",
  wordWrap: "break-word",
  overflow: "hidden",
  whiteSpace: "normal",

};
