export const TextBox = {
  name: "TextBox1",
  type: "TextBox",
  autoSize: false,
  autoTab: false,
  autoWordSelect: true,
  controlSource: "",
  controlTipText: "",
  dragBehaviour: "0 - fmDragBehaviotDisabled",
  enabled: true,
  enterFieldBehaviour: "0 - fmEnterFiledBehaviorSelectAll",
  enterKeyBehaviour: false,
  helpContextId: 0,
  hideSelection: true,
  integralHeight: true,
  imeMode: "0 - fmIMEModeNOControl",
  locked: false,
  maxLength: 0,
  mouseIcon: "(None)",
  multiLine: false,
  passwordChar: "",
  scrollBars: "1 - fmScrollBarsHorizontal",
  selectionMargin: true,
  tabindex: 4,
  tabKeyBehaviour: false,
  tabStop: false,
  tag: "",
  text: "",
  value: "",
  visible: true,
  left: "20px",
  top: "100px",
  width: "100px",
  height: "40px",
  zIndex: "1",
  backColor: "white",
  borderColor: "#eeeeee",
  border: "1px solid",
  borderStyle: "solid",
  font: "Arial, Helvetica, sans-serif",
  foreColor: "black",
  textAlign: "left",
  cursor: "default",
  specialEffect: "none",
  wordWrap: "break-word",
  overflow: "hidden",
  whiteSpace: "normal",

};
