export const userFormData = {
    property: {
            zIndex:"",
            position: "relative",
            textAlign: "left",
            border: "none",
            width: "400px",
            height: "250px",
            resize: "both",
            overflow: "hidden",
            borderTopLeftRadius: "4px",
            borderTopRightRadius: "4px",
            maxWidth: "98%",
            maxHeight: "88%",
            margin: "4px",
            backColor: "white",
            borderColor: "ghostwhite",
            font: "Tahoma",
            foreColor: "black",
            left: "0",
            top: "0",
            zoom: "100%",
            mousePointer: "0 - fmMousePointerDefault",
            specialEffect: "none",
            pictureSizeMode: " 9px 10px",
            picture: "radial-gradient(circle, rgb(0, 0, 0) 0.5px, rgba(0, 0, 0, 0) 0.2px)",
            controlZIndex: "3",
            name: "UserForm1",
            type: "UserForm",
            visible: true,
            autoSize: false,
            caption: "UserForm1",
            cycle: "0 - fmCycleAllForms",
            drawBuffer: 32000,
            enabled: true,
           /*  backgroundPosition:"center",
            backgroundPositionX:"",
            backgroundPositionY:"", */
            helpContextId: 0,
            keepScrollsBarsVisible: "fmScrollBarsNone",
            mouseIcon: "(None)",
            // picture: "(None)",
            pictureAlignment: "0 - fmPictureAlignmentTopLeft",
            // pictureSizeMode: "0 - fmPictureSizeModeClip",
            pictureTiling: false,
            rightToLeft: false,
            scrollBars: "0 - fmScrollBarsNone",
            scrollHeight: 0,
            scrollLeft: 0,
            scrollTop: 0,
            startUpPosition: "0 - Manual",
            scrollWidth: 0,
            showModal: true,
            tag: "",
            whatsThisButton: false,
            whatsThisHelp: false,
            display: "block",
            outerWindowZIndex: "2",
            outerWindowtop: "50px",
            outerWindowleft: "50px",
          },
          controls: {},

}